# Generated by Django 3.2.8 on 2023-12-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('kilometer', models.PositiveBigIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('ad_type', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('fuel', models.CharField(blank=True, max_length=50)),
                ('engine', models.CharField(blank=True, max_length=50)),
                ('chassis', models.CharField(blank=True, max_length=50)),
                ('chassis_front', models.CharField(blank=True, max_length=50)),
                ('chassis_back', models.CharField(blank=True, max_length=50)),
                ('body', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(blank=True, max_length=50)),
                ('gearbox', models.CharField(blank=True, max_length=50)),
                ('can_exchange', models.CharField(blank=True, max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(default='')),
                ('appointment', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('CALL_WAIT', 'Call Wait'), ('NO_ANSWER', 'No Answer'), ('SOLD', 'Sold')], default='CALL_WAIT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
