# Generated by Django 3.2.8 on 2022-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='credit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='credit_discount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='credit_final',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='debit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='debit_discount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='debit_final',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='dkpc',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
