# Generated by Django 3.2.8 on 2022-10-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20220613_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='dkpc',
            field=models.PositiveBigIntegerField(),
        ),
    ]
