# Generated by Django 3.2.8 on 2023-11-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20221120_1841'),
        ('accounting', '0005_alter_invoiceitem_dkpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceActualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('actual_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_product_items', to='products.actualproduct')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_product_items', to='accounting.invoice')),
            ],
        ),
    ]
