# Generated by Django 3.2.8 on 2023-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_invoiceactualitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
