# Generated by Django 3.2.8 on 2021-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211007_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='has_competition',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
