# Generated by Django 3.2.8 on 2021-10-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211014_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='actual_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.actualproduct'),
        ),
    ]
