# Generated by Django 3.2.8 on 2021-11-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211016_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('code', models.IntegerField()),
                ('date_persian', models.CharField(max_length=255)),
                ('dkpc', models.IntegerField()),
                ('variant_title', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('serial', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('credit_discount', models.IntegerField()),
                ('debit_discount', models.IntegerField()),
                ('credit_final', models.IntegerField()),
                ('debit_final', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('calculated', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.invoice')),
            ],
        ),
    ]
