# Generated by Django 3.2.8 on 2022-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_step',
            field=models.IntegerField(default=500),
        ),
    ]
