# Generated by Django 3.2.8 on 2022-01-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='end_date',
            new_name='end_date_persian',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='start_date',
            new_name='start_date_persian',
        ),
    ]
