# Generated by Django 3.2.8 on 2022-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220122_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stop_loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
