# Generated by Django 3.2.8 on 2022-02-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_producttypeselectorvalue_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants_fk', to='products.producttypeselectorvalue'),
        ),
    ]
