# Generated by Django 3.2.8 on 2022-02-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariant_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_types_fk', to='products.producttypeselector'),
        ),
    ]
