# Generated by Django 3.2.8 on 2022-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_dkpc_productvariant_dkpc_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dkpc',
            field=models.IntegerField(null=True),
        ),
    ]
