# Generated by Django 3.2.8 on 2022-02-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productvariant_dkpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='dkpc_old',
        ),
    ]
