# Generated by Django 3.2.8 on 2022-09-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_productvariant_dkpc_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='selector',
            new_name='selector_type',
        ),
        migrations.RenameField(
            model_name='producttypeselectorvalue',
            old_name='selector',
            new_name='selector_type',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='selectors',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selector_values',
        ),
    ]
