# Generated by Django 3.2.8 on 2022-09-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20220915_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='selector_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_types', to='products.variantselectortype'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.variantselector'),
        ),
    ]
