# Generated by Django 3.2.8 on 2022-10-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_producttype_selector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='actual_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.actualproduct'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.variantselector'),
        ),
    ]
