# Generated by Django 3.2.8 on 2022-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20221008_2317'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'selector'), name='unique_product_selector'),
        ),
    ]
