# Generated by Django 3.2.8 on 2022-10-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productvariant_unique_product_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stop_loss',
            field=models.IntegerField(default=0),
        ),
    ]
