# Generated by Django 3.2.8 on 2022-11-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productvariant_dkpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dkp',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variantselector',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variantselectortype',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
